<a href="https://colab.research.google.com/github/jayalaxmikonchady-web/jaya1/blob/main/EXP8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#package imports
import pandas as pd
import missingno as msno
%matplotlib inline

In [ ]:
#importingtherequireddataset
titanic_df=pd.read_csv('/content/test.csv')
print(titanic_df)
print(titanic_df.info())
print(titanic_df.isnull())
print(titanic_df.isnull().sum())
df=titanic_df.dropna(axis=0)
df.isnull().sum()
df.info()
print(titanic_df.columns)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

[418 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB
None
     PassengerId  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  \
0          False   False  False  False  False  False  False   False  False
1          False   False  False  False  False  False  False   False  False
2          False   False  False  False  False  False  False   False  False
3          False   False  False  False  False  False  False   False  False
4          False   False  False  False  False  False  False   False  False
..           ...     ...    ...    ...    ...    ...    ...     ...    ...
413        False   False  False  False   True  False  False   False  False
414        False   False  False  False  False  False  False   False  False
415        False   False  False  False  False  False  False   False  False
416        False   False  False  False   True  False  False   False  False
417        False   False  False  False   True  False  False   False  False

     Cabin  Embarked
0     True     False
1     True     False
2     True     False
3     True     False
4     True     False
..     ...       ...
413   True     False
414  False     False
415   True     False
416   True     False
417   True     False

[418 rows x 11 columns]
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 87 entries, 12 to 414
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  87 non-null     int64
 1   Pclass       87 non-null     int64
 2   Name         87 non-null     object
 3   Sex          87 non-null     object
 4   Age          87 non-null     float64
 5   SibSp        87 non-null     int64
 6   Parch        87 non-null     int64
 7   Ticket       87 non-null     object
 8   Fare         87 non-null     float64
 9   Cabin        87 non-null     object
 10  Embarked     87 non-null     object
dtypes: float64(2), int64(4), object(5)
memory usage: 8.2+ KB
Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df=titanic_df.drop(['Fare'],axis=1)
print(df.isnull().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Cabin          327
Embarked         0
dtype: int64

In [ ]:
print(titanic_df['Fare'].unique())

[  7.8292   7.       9.6875   8.6625  12.2875   9.225    7.6292  29.
   7.2292  24.15     7.8958  26.      82.2667  61.175   27.7208  12.35
   7.225    7.925   59.4      3.1708  31.6833  61.3792 262.375   14.5
  61.9792  30.5     21.6792  31.5     20.575   23.45    57.75     8.05
   9.5     56.4958  13.4167  26.55     7.85    13.      52.5542  29.7
   7.75    76.2917  15.9     60.      15.0333  23.     263.      15.5792
  29.125    7.65    16.1     13.5      7.725   21.       7.8792  42.4
  28.5375 211.5     25.7     15.2458 221.7792  10.7083  14.4542  13.9
   7.775   52.       7.7958  78.85     7.8542  55.4417   8.5167  22.525
   7.8208   8.7125  15.0458   7.7792  31.6792   7.2833   6.4375  16.7
  75.2417  15.75     7.25    23.25    28.5     25.4667  46.9    151.55
  18.      51.8625  83.1583      nan  12.1833  31.3875   7.55    13.775
   7.7333  22.025   50.4958  34.375    8.9625  39.      36.75    53.1
 247.5208  16.      69.55    32.5    134.5     10.5      8.1125  15.5
  14.4    227.525   25.7417   7.05    73.5     42.5    164.8667  13.8583
  27.4458  15.1     65.       6.4958  71.2833  75.25   106.425   30.
   7.8875  27.75   136.7792   9.325   17.4     12.7375   0.      20.2125
  39.6      6.95    81.8583  41.5792  45.5      9.35    93.5     14.1083
   7.575  135.6333 146.5208 211.3375  79.2     15.7417   7.5792 512.3292
  63.3583  51.4792  15.55    37.0042  14.4583  39.6875  11.5     50.
  12.875   21.075   39.4     20.25    47.1     13.8625   7.7208  90.
 108.9     22.3583]

In [ ]:
titanic_df['Fare']=titanic_df['Fare'].fillna('C')

In [ ]:
print(titanic_df['Fare'].isnull().sum())

0

In [ ]:
print(titanic_df)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket     Fare Cabin Embarked
0      male  34.5      0      0              330911   7.8292   NaN        Q
1    female  47.0      1      0              363272      7.0   NaN        S
2      male  62.0      0      0              240276   9.6875   NaN        Q
3      male  27.0      0      0              315154   8.6625   NaN        S
4    female  22.0      1      1             3101298  12.2875   NaN        S
..      ...   ...    ...    ...                 ...      ...   ...      ...
413    male   NaN      0      0           A.5. 3236     8.05   NaN        S
414  female  39.0      0      0            PC 17758    108.9  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262     7.25   NaN        S
416    male   NaN      0      0              359309     8.05   NaN        S
417    male   NaN      1      1                2668  22.3583   NaN        C

[418 rows x 11 columns]

In [ ]:
mean=titanic_df['Age'].mean()
print(mean)
titanic_df['Age']=titanic_df['Age'].fillna(mean)
titanic_df['Age']

30.272590361445783

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [ ]:
titanic_df=pd.read_csv('/content/test.csv')
mode=titanic_df['Fare'].mode()[0]
print(mode)
titanic_df['Fare']=titanic_df['Fare'].fillna(mode)
print(titanic_df['Fare'])

7.75
0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [ ]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].median())
print(titanic_df['Age'])

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ...
413    27.0
414    39.0
415    38.5
416    27.0
417    27.0
Name: Age, Length: 418, dtype: float64

In [ ]:
new_df=titanic_df.fillna(method="ffill")
new_df

/tmp/ipykernel_616/2823126361.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=titanic_df.fillna(method="ffill")

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,28.0,0,0,A.5. 3236,8.0500,C78,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,C105,S
416,1308,3,"Ware, Mr. Frederick",male,38.5,0,0,359309,8.0500,C105,S
417,1309,3,"Peter, Master. Michael J",male,38.5,1,1,2668,22.3583,C105,C

In [43]:
new_df=titanic_df.fillna(method="ffill",limit=1)
new_df

/tmp/ipykernel_616/3198877977.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=titanic_df.fillna(method="ffill",limit=1)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,28.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,C105,S
416,1308,3,"Ware, Mr. Frederick",male,38.5,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [44]:
new_df=titanic_df.fillna(method="bfill")
new_df

/tmp/ipykernel_616/2509177895.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=titanic_df.fillna(method="bfill")

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B45,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B45,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B45,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B45,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B45,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,39.0,0,0,A.5. 3236,8.0500,C105,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [45]:
new_df=titanic_df.fillna(method="bfill",limit=1)
new_df

/tmp/ipykernel_616/1240764193.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df=titanic_df.fillna(method="bfill",limit=1)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,39.0,0,0,A.5. 3236,8.0500,C105,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C